version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ecs-fargate-task-with-efs-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13v3pefdyn46p"
s3_prefix = "ecs-fargate-task-with-efs-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VpcId=\"vpc-2708bf40\" SubnetID=\"subnet-058724041d8b0811a\" SecurityGroupIDs=\"sg-90433feb\""
image_repositories = []
