version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ecs-fargate-load-balanced-http-service-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13v3pefdyn46p"
s3_prefix = "ecs-fargate-load-balanced-http-service-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
